#!/usr/bin/env python3
"""
Costraca Backup Executor Tool
Executes backup plans generated by Stopoda with dry-run first + confirmation
"""

import os
import sys
import json
import subprocess
import hashlib
import logging
from pathlib import Path
from datetime import datetime

LOG_DIR = Path("/a0/output")
LOG_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "audit.log"),
        logging.StreamHandler()
    ]
)
log = logging.getLogger("costraca.backup")


def run_command(cmd: list, dry_run: bool = True) -> tuple[int, str, str]:
    """Run a shell command safely, returns (returncode, stdout, stderr)."""
    if dry_run and "--dry-run" not in cmd:
        cmd = cmd + ["--dry-run"]

    log.info(f"Executing: {' '.join(cmd)}")
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,
            check=False
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return 1, "", "Command timed out after 300 seconds"
    except Exception as e:
        return 1, "", str(e)


def validate_backup_plan(plan_file: str) -> dict:
    """Load and validate a backup plan JSON file."""
    path = Path(plan_file)
    if not path.exists():
        raise FileNotFoundError(f"Backup plan not found: {plan_file}")

    with open(path) as f:
        plan = json.load(f)

    required_keys = ["scan_info", "findings", "backup_plan"]
    for key in required_keys:
        if key not in plan:
            raise ValueError(f"Invalid backup plan: missing key '{key}'")

    return plan


def check_disk_space(backup_base: str, findings: dict) -> dict:
    """Check if destination has enough space for backup."""
    total_size = sum(
        item["size_bytes"]
        for level in ["critical", "high", "medium"]
        for item in findings.get(level, [])
    )

    dest = Path(backup_base).parent
    dest.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(["df", "-B1", str(dest)], capture_output=True, text=True)
    available = 0
    for line in result.stdout.strip().split('\n')[1:]:
        parts = line.split()
        if len(parts) >= 4:
            try:
                available = int(parts[3])
            except ValueError:
                pass

    return {
        "required_bytes": total_size,
        "available_bytes": available,
        "sufficient": available > total_size * 1.1,  # 10% buffer
        "required_human": f"{total_size / 1024 / 1024:.1f} MB",
        "available_human": f"{available / 1024 / 1024:.1f} MB"
    }


def execute_backup(plan_file: str, dry_run: bool = True) -> dict:
    """
    Execute backup from plan.
    Always runs dry-run first. Real execution only if dry_run=False and confirmed.
    """
    log.info(f"Loading backup plan: {plan_file}")
    plan = validate_backup_plan(plan_file)

    backup_base = plan["backup_plan"]["backup_base"]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dest = f"{backup_base}_{timestamp}" if not dry_run else backup_base

    # Disk space check
    space = check_disk_space(backup_dest, plan["findings"])
    print(f"\n[*] Disk space check:")
    print(f"    Required:  {space['required_human']}")
    print(f"    Available: {space['available_human']}")
    if not space["sufficient"]:
        log.error("Insufficient disk space for backup!")
        return {"error": "Insufficient disk space", "space": space}

    results = {"dry_run": dry_run, "timestamp": timestamp, "operations": []}
    mode = "DRY RUN" if dry_run else "ACTUAL BACKUP"

    print(f"\n{'='*60}")
    print(f"BACKUP EXECUTION - {mode}")
    print(f"{'='*60}")

    for level in ["critical", "high", "medium"]:
        items = plan["findings"].get(level, [])
        if not items:
            continue

        dest_dir = f"{backup_dest}/{level}/"
        os.makedirs(dest_dir, exist_ok=True)

        print(f"\n[{level.upper()}] - {len(items)} files")
        for item in items:
            src = item["path"]
            if not Path(src).exists():
                log.warning(f"Source not found, skipping: {src}")
                results["operations"].append({"src": src, "status": "skipped", "reason": "not found"})
                continue

            cmd = ["rsync", "--verbose", "--checksum", "--human-readable",
                   "--itemize-changes", src, dest_dir]
            if dry_run:
                cmd.insert(1, "--dry-run")

            rc, stdout, stderr = run_command(cmd, dry_run=False)  # cmd already has --dry-run if needed
            status = "success" if rc == 0 else "failed"

            op = {"src": src, "dest": dest_dir, "status": status, "returncode": rc}
            if stderr:
                op["stderr"] = stderr
            results["operations"].append(op)
            print(f"  {'OK' if rc == 0 else 'FAIL'} {src}")

    # Save results
    report_path = LOG_DIR / f"backup_report_{timestamp}.json"
    with open(report_path, "w") as f:
        json.dump(results, f, indent=2)

    # Generate integrity checksums
    if not dry_run:
        checksum_file = LOG_DIR / f"backup_checksums_{timestamp}.sha256"
        with open(checksum_file, "w") as f:
            for op in results["operations"]:
                if op["status"] == "success":
                    h = hashlib.sha256()
                    try:
                        with open(op["src"], "rb") as src_f:
                            h.update(src_f.read())
                        f.write(f"{h.hexdigest()}  {op['src']}\n")
                    except (PermissionError, OSError):
                        pass
        log.info(f"Checksums saved to: {checksum_file}")

    success_count = sum(1 for op in results["operations"] if op["status"] == "success")
    fail_count = sum(1 for op in results["operations"] if op["status"] == "failed")

    print(f"\n{'='*60}")
    print(f"Results: {success_count} succeeded, {fail_count} failed")
    print(f"Report saved: {report_path}")

    if dry_run:
        print(f"\n[!] This was a DRY RUN. No files were actually copied.")
        print(f"    To execute real backup, run with --execute flag.")

    return results


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <plan.json> [--execute]")
        sys.exit(1)

    plan_file = sys.argv[1]
    execute = "--execute" in sys.argv

    if execute:
        print("\n[!] REAL BACKUP MODE - This will copy files.")
        print("    Confirm: YES to proceed, anything else to abort: ", end="")
        confirm = input().strip()
        if confirm != "YES":
            log.info("Backup aborted by user.")
            sys.exit(0)

    execute_backup(plan_file, dry_run=not execute)
